algoritmo "inicial"
// Função :
// Autor : Giovana Campos
// Data : 19/09/2022
// Seção de Declarações

var
nota1, nota2,alunos: inteiro
media:real

inicio
para alunos de 1 ate 10 faca
escreval("Digite a primeira nota do aluno(a):")
  leia(nota1)
escreval("Digite a segunda nota do aluno(a):")
  leia(nota2)
media <-(nota1+nota2)/2
escreval("A média do aluno" , alunos, " é:", media)
escreval()
fimpara
fimalgoritmo

