algoritmo "semnome"
// Função :
// Autor :
// Data : 19/09/2022
// Seção de Declarações 
var
nota1, nota2, alunos: inteiro
média: real

inicio
para alunos de 1 ate 10 faca
     escreval("Digite a primeira nota:")
     leia(n1)
     escreval("Digite a segunda nota:")
     leia(n2)
     media <- (nota1 + nota2)/2
     escreval("A média do aluno" , alunos, " é:", media)
     escreval()
fimpara
fimalgoritmo

