algoritmo "ESTRUTURA CONDICIONAL"
// Função : Identificar se um número é par ou ímpar
// Autor : Giovana Campos
// Data : 20/06/2022
// Seção de Declarações 
var
num:inteiro

inicio

escreval("Digite um número")
leia(num)

se num < 0 entao
 //VERDADEIRO
 escreval("NEGATIVO")
senao
//FALSO
 se num > 0 entao
 //VERDADEIRO
 escreval("POSITIVO")
senao
 //FALSO
 escreval("ZERO")
 fimse
fimse

fimalgoritmo
