algoritmo "Algoritmo Converte_dolar"

var
cotacao,valor_reais,valçor_dolar:real
inicio
// Seção de Comandos 
escreval("Digite o valor em reais da cotação do dólar: ")
leia(cotacao)
escreval("Digite a quantia em reais que você deseja converter para dólares: ")
leia(valor_reais)

//Processamento
valor_dolar<- valor_reais/cotacao

//Dados de Saída
escreval("O valor convertido equivalea US$ ",valor_dolar)





fimalgoritmo
